# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'agent-devops'

steps:
- script: echo 1.'$(Rev:r)'
# - task: Docker@2
#   displayName: 'Build and Push Docker Image'
#   inputs:
#     containerRegistry: 'Azure Container Registry'
#     repository: 'test'
#     command: 'buildAndPush'
#     Dockerfile: 'Dockerfile'
# - task: KubectlInstaller@0
#   displayName: Choose kubectl v.1.22
#   inputs: 
#     kubectlVersion: 1.22.0
# - task: Kubernetes@1
#   displayName: Deploy to Azure Kubernetes Service
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Azure Resource Manager'
#     azureResourceGroup: 'ciz-npr1-d-rsg-aks-dta'
#     kubernetesCluster: 'ciz-npr1-d-aks-cluster01'
#     namespace: test
#     command: 'apply'
#     arguments: '-f test-deployment.yaml'