# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'agent-devops'

steps:
# - task: Docker@2
#   displayName: 'Build and Push Docker Image'
#   inputs:
#     containerRegistry: 'Azure Container Registry'
#     repository: 'wlz-ciz-client-portal-3'
#     command: 'buildAndPush'
#     Dockerfile: 'Dockerfile'
- task: KubectlInstaller@0
  displayName: Kubectl installer
  inputs: 
    kubectlVersion: 1.22.0
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure Resource Manager'
    azureResourceGroup: 'ciz-cicd-c-rsg-aks-pega'
    kubernetesCluster: 'ciz-cicd-d-aks-cluster01'
    #namespace: test
    command: 'get'
    arguments: 'nodes'