apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cizpriprocesshwtilbmefbyo2.azurecr.io/wlz-ciz-client-portal-3:72
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginx
  name: nginx-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
spec:
  rules:
  - host: nginx.cizpriprocess.local
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /*
        backend:
          service:
            name: nginx
            port:
              number: 80
